# === COLORES ===
COLOR_FONDO = "#1a1a2e"
COLOR_FONDO_SECUNDARIO = "#16213e"
COLOR_ACENTO = "#0f3460"
COLOR_BOTON_PRIMARY = "#e94560"
COLOR_BOTON_SUCCESS = "#28a745"
COLOR_BOTON_WARNING = "#fd7e14"
COLOR_BOTON_HOVER = "#c23854"
COLOR_TEXTO = "#ffffff"
COLOR_TEXTO_SECUNDARIO = "#a0a0a0"

# Colores para puertas
COLOR_PUERTA_CERRADA = "#8B4513"
COLOR_PUERTA_ABIERTA = "#9370DB"
COLOR_PUERTA_SELECCIONADA = "#FFD700"

# Colores para cartas
COLOR_CARTA_DORSO = "#4169E1"
COLOR_CARTA_FRENTE = "#FFFFFF"
COLOR_CARTA_ROJA = "#DC143C"
COLOR_CARTA_NEGRA = "#000000"

# === TAMAÑOS ===
ANCHO_VENTANA = 1200
ALTO_VENTANA = 700

# === FUENTES ===
FUENTE_TITULO = ("Arial", 32, "bold")
FUENTE_SUBTITULO = ("Arial", 18)
FUENTE_BOTON = ("Arial", 14, "bold")
FUENTE_TEXTO = ("Arial", 12)
FUENTE_CARTA = ("Arial", 10, "bold")
